skyceh/skyceh/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from orders import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from tsk1.views import (
    add_plasma_task,
    TaskView,
    TaskDetailView,
    ComTaskView,
)
from orders.views import OrdInvList
from plasma.views import (
    view_plasma_task,
    view_com_plasma_task,
    do_plasma_task,
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", login_required(views.OrderListView.as_view()), name="home"),
    path("statusupdate/<int:znum>", login_required(views.StatusUpdate), name="stupd"),
    path(
        "create/", login_required(views.OrderCreateView.as_view()), name="order_create"
    ),
    re_path(r"^orders/$", login_required(views.OrderListView.as_view()), name="orders"),
    re_path(
        r"^complete/$", login_required(views.ComOrderView.as_view()), name="com-orders"
    ),
    re_path(
        r"^order/(?P<pk>\d+)$",
        login_required(views.OrderDetailView.as_view()),
        name="order-detail",
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path("logout/", login_required(views.logout_view), name="logout"),
    re_path(r"^inv/(?P<pk>\d+)$", login_required(OrdInvList), name="invsort"),
    path("newplasmatask/", login_required(add_plasma_task), name="newplasmatask"),
    path("task/", login_required(TaskView.as_view()), name="task"),
    path(
        "task/<int:pk>/", login_required(TaskDetailView.as_view()), name="task-detail"
    ),
    path("plasma/task/", login_required(view_plasma_task), name="plasma_task"),
    path("dptask/<int:pk>/", login_required(do_plasma_task), name="do_plasma_task"),
    re_path(
        r"^task/complete/$", login_required(ComTaskView.as_view()), name="com-task"
    ),
    path(
        "plasma/comtask/", login_required(view_com_plasma_task), name="plasma_com_task"
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skyceh/orders/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


def generate_filename(instance, filename):
    # Генерация нового имени файла, включая znum в имя файла
    import os

    basefilename, file_extension = os.path.splitext(filename)
    new_filename = f"{instance.znum}{file_extension}"
    return os.path.join("", new_filename)


# БД с основными данными о заказе
class MainOrderInfo(models.Model):
    znum = models.IntegerField(
        verbose_name="Номер заказа", primary_key=True
    )  # номер заказа
    prod = models.CharField(verbose_name="Наименование изделия")  # наименование изделия
    count = models.IntegerField(verbose_name="Количество")  # количество
    client = models.CharField(verbose_name="Название заказчика")  # название заказчика
    invorder = models.CharField(verbose_name="Счет заказа")  # счет заказа
    lastday = models.DateField(verbose_name="Срок сдачи")  # срок сдачи
    status = models.CharField(verbose_name="Статус заказа", default="В работе")
    file = models.FileField(
        upload_to=generate_filename, blank=True, null=True, verbose_name="Файл"
    )

    class Meta:
        ordering = ["-znum"]
        verbose_name = "Заказы"

    def __str__(self):
        return str(self.znum)

    def get_absolute_url(self):
        return reverse("order-detail", args=[str(self.znum)])

skyceh/orders/forms.py
from django import forms
from .models import MainOrderInfo
from django.forms import modelformset_factory


class MainOrderInfoForm(forms.ModelForm):
    class Meta:
        model = MainOrderInfo
        fields = ["znum", "prod", "count", "client", "invorder", "lastday", "file"]


class OrderForm(forms.ModelForm):
    class Meta:
        model = MainOrderInfo
        fields = ["znum", "prod", "count", "client", "invorder", "lastday", "file"]
        widgets = {
            "lastday": forms.DateInput(attrs={"type": "date"}),
        }

skyceh/orders/views.py
from django.http import *
from .models import MainOrderInfo
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.shortcuts import render
from .forms import OrderForm


class OrderListView(generic.ListView):
    model = MainOrderInfo


class ComOrderView(generic.ListView):
    model = MainOrderInfo
    template_name = "orders/completed_list.html"


class OrderDetailView(generic.DetailView):
    model = MainOrderInfo


def StatusUpdate(request, znum):
    try:
        inf = MainOrderInfo.objects.get(znum=znum)
        if inf.status == "В работе":
            MainOrderInfo.objects.filter(znum=znum).update(status="Выполнен")
        else:
            MainOrderInfo.objects.filter(znum=znum).update(status="В работе")
        return HttpResponseRedirect("/")
    except MainOrderInfo.DoesNotExist:
        return HttpResponseNotFound("<h2>Заказ не найден</h2>")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/")


class OrderCreateView(generic.CreateView):
    model = MainOrderInfo
    form_class = OrderForm
    template_name = "orders/order_create.html"
    success_url = reverse_lazy("orders")  # Перенаправление после успешного создания


def OrdInvList(request, pk):
    try:
        zak = MainOrderInfo.objects.get(znum=pk)
        num = zak.invorder
        inv = MainOrderInfo.objects.filter(invorder=num)
        return render(request, "orders/inv_list.html", {"inv": inv})
    except MainOrderInfo.DoesNotExist:
        return HttpResponseNotFound("<h2>Счет не найлен</h2>")

skyceh/templates/orders/completed_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class="text-center">Выполненные заказы</h1>
{% if mainorderinfo_list %}
<table class="table table-hover table-info">
  <thead>
    <tr>
      <th scope="col">Заказ №</th>
      <th scope="col">Счет</th>
      <th scope="col">Изделие</th>

      <th scope="col">Количество</th>
      <th scope="col">Заказчик</th>

      <th scope="col">Срок сдачи</th>
      <th scope="col">Статус</th>
    </tr>
  </thead>
  <tbody>
    {% for order in mainorderinfo_list %}
    {% if order.status == 'Выполнен' %}
    <tr>
      <th scope="row">
        <a href="{{ order.get_absolute_url }}">{{ order.znum }}</a>
      </th>
      <td>{{ order.invorder }}</td>
      <td><a href="{{ order.get_absolute_url }}">{{ order.prod }}</a></td>
      <td>{{ order.count }}</td>
      <td>{{ order.client }}</td>

      <td>{{ order.lastday }}</td>
      <td>Выполнен</td>
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>
{% endif %}
{% endblock %}

skyceh/templates/orders/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Main page</h1>
<p>Welcome</p>
<h2>Dynamic content</h2>
<p>Now count orders in DB :</p>
<ul>
    <li><strong>Count orders:</strong> {{ num_ord }}</li>
    <li><strong>Count item:</strong> {{ num_dord }}</li>
</ul>
{% endblock %}

skyceh/templates/orders/inv_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class="text-center">Заказы в работе</h1>
{% if inv %}
<table class="table table-hover table-info">
    <thead>
        <tr>
            <th scope="col">Заказ №</th>
            <th scope="col">Счет</th>
            <th scope="col">Изделие</th>
            <th scope="col">Количество</th>
            <th scope="col">Заказчик</th>

            <th scope="col">Срок сдачи</th>
            <th scope="col">Статус</th>
        </tr>
    </thead>
    <tbody>
        {% for i1 in inv %}
        <tr>
            <th scope="row">
                <a href="{{ i1.get_absolute_url }}">{{ i1.znum }}</a>
            </th>
            <td>{{ i1.invorder }}</td>
            <td><a href="{{ i1.get_absolute_url }}">{{ i1.prod }}</a></td>
            <td>{{ i1.count }}</td>
            <td>{{ i1.client }}</td>

            <td>{{ i1.lastday }}</td>
            <td>{{ i1.status }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>Not orders in BD</p>
{% endif %}
{% endblock %}

skyceh/templates/orders/logged_out.html
<!-- registration/logged_out.html -->
{% extends 'base_generic.html' %}

{% block content %}
<h2>Вы успешно вышли из системы.</h2>
{% endblock %}

skyceh/templates/orders/mainorderinfo_detail.html
{% extends "base_generic.html" %}
{% load custom_filters %}
{% block content %}

<div class="text-center fw-semibold fs-2">{{ mainorderinfo.prod }} / {{ mainorderinfo.count }} шт. / <text
        class="fw-bold"> Зав. заказ №{{ mainorderinfo.znum }} </text> <br> заказчик {{ mainorderinfo.client }} / Счет
    №{{ mainorderinfo.invorder }} / <text class="fw-bold"> срок до {{ mainorderinfo.lastday }} </text>/
    Статус: {{ mainorderinfo.status }}
    {% if user|is_in_group:'chief' %}
    {% if mainorderinfo.status == 'В работе' %}
    <a class="btn btn-primary btn-lg" href="{% url 'stupd' znum=mainorderinfo.znum %}" role="button">Заказ выполнен</a>
    {% else %}
    <a class="btn btn-primary btn-lg" href="{% url 'stupd' znum=mainorderinfo.znum %}" role="button">Вернуть в
        работу</a>
    {% endif %}
    {% endif %}
</div>



<div class="container-fluid">
    <div class="col text-center">
        <embed src="{{ mainorderinfo.file.url }}" type="application/pdf" width="100%" height="500px">
    </div>
</div>



{% endblock %}

skyceh/templates/orders/mainorderinfo_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class="text-center">Заказы в работе</h1>
{% if mainorderinfo_list %}
<table class="table table-hover table-info">
  <thead>
    <tr>
      <th scope="col">Заказ №</th>
      <th scope="col">Счет</th>
      <th scope="col">Изделие</th>
      <th scope="col">Количество</th>
      <th scope="col">Заказчик</th>

      <th scope="col">Срок сдачи</th>
      <th scope="col">Статус</th>
    </tr>
  </thead>
  <tbody>
    {% for order in mainorderinfo_list %}
    {% if order.status == 'В работе' %}
    <tr>
      <th scope="row">
        <a href="{{ order.get_absolute_url }}">{{ order.znum }}</a>
      </th>
      <td><a href="{% url 'invsort' order.znum %}">{{ order.invorder }}</a></td>
      <td><a href="{{ order.get_absolute_url }}">{{ order.prod }}</a></td>
      <td>{{ order.count }}</td>
      <td>{{ order.client }}</td>

      <td>{{ order.lastday }}</td>
      <td>В работе</td>
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>
{% endif %}
{% endblock %}

skyceh/templates/orders/order_create.html
{% extends "base_generic.html" %}

{% block content %}

<body class="bg-body-tertiary">
	<div class="container">
		<main>
			<div class="row g-5">
				<div class="col-md-7 col-lg-8">
					<h2 class="mb-3">Новый заказ</h2>
					<form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
						{% csrf_token %}
						<div class="row g-3">
							<div class="col-sm-3">
								<label for="firstName" class="form-label">Номер заказа</label>
								<input type="text" class="form-control" id="firstName" placeholder="" value=""
									name="znum" required>
							</div>
							<div class="col-sm-3">
								<label for="firstName" class="form-label">Количество</label>
								<input type="text" class="form-control" id="firstName" placeholder="" value=""
									name="count" required>
							</div>
							<div class="col-sm-6">
								<label for="firstName" class="form-label">Счет</label>
								<input type="text" class="form-control" id="firstName" placeholder="" value=""
									name="invorder" required>
							</div>
							<div class="col-sm-12">
								<label for="firstName" class="form-label">Изделие</label>
								<input type="text" class="form-control" id="firstName" placeholder="" value=""
									name="prod" required>
							</div>
							<div class="col-sm-12">
								<label for="firstName" class="form-label">Заказчик</label>
								<input type="text" class="form-control" id="firstName" placeholder="" value=""
									name="client" required>
							</div>
							<div class="col-sm-3">
								<label for="firstName" class="form-label">Срок сдачи</label>
								<input type="date" class="form-control" id="firstName" placeholder="" value=""
									name="lastday" required>
							</div>
							<div class="col-sm-9">
								<label for="formFile" class="form-label">Файл</label>
								<input class="form-control" type="file" id="formFile" name="file" required>
							</div>
						</div>
						<hr class="my-4">
						<button class="w-100 btn btn-primary btn-lg" type="submit">Добавить заказ</button>
					</form>
				</div>
			</div>
		</main>
	</div>
</body>
{% endblock %}