skyceh/skyceh/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from orders import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from tsk1.views import (
    add_plasma_task,
    TaskView,
    TaskDetailView,
    ComTaskView,
)
from orders.views import OrdInvList
from plasma.views import (
    view_plasma_task,
    view_com_plasma_task,
    do_plasma_task,
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", login_required(views.OrderListView.as_view()), name="home"),
    path("statusupdate/<int:znum>", login_required(views.StatusUpdate), name="stupd"),
    path(
        "create/", login_required(views.OrderCreateView.as_view()), name="order_create"
    ),
    re_path(r"^orders/$", login_required(views.OrderListView.as_view()), name="orders"),
    re_path(
        r"^complete/$", login_required(views.ComOrderView.as_view()), name="com-orders"
    ),
    re_path(
        r"^order/(?P<pk>\d+)$",
        login_required(views.OrderDetailView.as_view()),
        name="order-detail",
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path("logout/", login_required(views.logout_view), name="logout"),
    re_path(r"^inv/(?P<pk>\d+)$", login_required(OrdInvList), name="invsort"),
    path("newplasmatask/", login_required(add_plasma_task), name="newplasmatask"),
    path("task/", login_required(TaskView.as_view()), name="task"),
    path(
        "task/<int:pk>/", login_required(TaskDetailView.as_view()), name="task-detail"
    ),
    path("plasma/task/", login_required(view_plasma_task), name="plasma_task"),
    path("dptask/<int:pk>/", login_required(do_plasma_task), name="do_plasma_task"),
    re_path(
        r"^task/complete/$", login_required(ComTaskView.as_view()), name="com-task"
    ),
    path(
        "plasma/comtask/", login_required(view_com_plasma_task), name="plasma_com_task"
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skyceh/tasks/models.py
from django.db import models

# Create your models here.


class SpotList(models.Model):
    SPOTS = ((None, "Выберите участок"), ("плазма", "плазма"))
    man = models.CharField(verbose_name="ФИО сотрудника", primary_key=True)
    spot = models.CharField(choices=SPOTS)


class TaskList(models.Model):
    date = models.DateField()
    task = models.TextField()
    file = models.FileField()
    man = models.ForeignKey(SpotList, on_delete=models.PROTECT)
    deadline = models.DateField()

skyceh/tsk1/models.py
from django.db import models
from datetime import date
from django.urls import reverse

# Create your models here.


class Task(models.Model):
    SPOTS = (
        (None, "Выберите участок"),
        ("плазма", "плазма"),
    )
    dat = models.DateField(default=date.today, verbose_name="Дата")
    task = models.TextField(verbose_name="Задача")
    file = models.FileField(blank=True, null=True, verbose_name="Файл")
    image = models.ImageField(blank=True, null=True, verbose_name="Изображение")
    now = models.IntegerField(default=0, verbose_name="Готово")
    total = models.IntegerField(default=1, verbose_name="Всего")
    spot = models.CharField(choices=SPOTS, max_length=30, verbose_name="Участок")
    man = models.CharField(verbose_name="ФИО сотрудника", max_length=30)
    deadline = models.DateField(default=date.today, verbose_name="Срок")
    ready = models.BooleanField(default=False)

    class Meta:
        ordering = ["-dat"]
        verbose_name = "Задачи"

    def get_absolute_url(self):
        return reverse("task-detail", kwargs={"pk": self.pk})

skyceh/tasks/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import TaskList, SpotList

# Create your views here.


class SpotListCreate(generic.CreateView):
    model = SpotList
    fields = ["man", "spot"]
    template_name = "tasks/spot_create.html"
    success_url = reverse_lazy("home")  # Перенаправление после успешного создания


class TaskListCreate(generic.CreateView):
    model = TaskList
    fields = ["date", "task", "file", "man", "deadline"]
    template_name = "tasks/task_create.html"
    success_url = reverse_lazy("home")  # Перенаправление после успешного создания

skyceh/templates/tasks/completed_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class="text-center">Задачи в работе</h1>
{% if task_list %}
<table class="table table-hover table-info">
    <thead>
        <tr>
            <th scope="col">Дата</th>
            <th scope="col">Задача</th>
            <th scope="col">Файл</th>
            <th scope="col">Изображение</th>
            <th scope="col">Участок</th>
            <th scope="col">Срок</th>
        </tr>
    </thead>
    <tbody>
        {% for task in task_list %}
        {% if task.ready == True %}
        <tr>
            <th scope="row">
                <a href="#">{{ task.dat }}</a>
            </th>
            <td><a href="{{ task.get_absolute_url }}">{{ task.task }}</a></td>
            {% if task.file %}
            <td>
                Файл: <a href="{{ task.file.url }}">{{ task.file.name }}</a>
            </td>
            {% else %}
            <td>
                Файл не загружен.
            </td>
            {% endif %}

            {% if task.image %}
            <td>
                Изображение: <img src="{{ task.image.url }}" alt="{{ task.image.name }}">
            </td>
            {% else %}
            <td>
                Изображение не загружено.
            </td>
            {% endif %}
            <td>{{ task.man }}</td>
            <td>{{ task.deadline }}</td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endif %}


{% endblock %}

skyceh/templates/tasks/newtask.html
{% extends "base_generic.html" %}

{% block content %}

<body class="bg-body-tertiary">
    <div class="container">
        <main>
            <div class="row g-5">
                <div class="col-md-7 col-lg-8">
                    <h2 class="mb-3">Новая задача для плазмы</h2>
                    <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-8">
                                <label for="id_man" class="form-label">Ответственный</label>
                                <select class="form-control" id="id_man" name="man" required>
                                    <option value="" selected disabled>Выберите ответственного</option>
                                    <option value="оператор чпу">оператор ЧПУ</option>
                                </select>
                            </div>
                            <div class="col-sm-4">
                                <label for="firstName" class="form-label">Срок</label>
                                <input type="date" class="form-control" id="firstName" placeholder="" value=""
                                    name="deadline" required>
                            </div>
                            <div class="col-sm-12">
                                <label for="firstName" class="form-label">Задача</label>
                                <input type="text" class="form-control" id="firstName" placeholder="" value=""
                                    name="task" required>
                            </div>
                            <div class="col-sm-9">
                                <label for="formFile" class="form-label">Файл</label>
                                <input class="form-control" type="file" id="formFile" name="file" required>
                            </div>
                            <div class="col-sm-3">
                                <label for="firstName" class="form-label">Количество</label>
                                <input type="text" class="form-control" id="firstName" placeholder="" value=""
                                    name="total" required>
                            </div>
                            <div class="col-sm-12">
                                <label for="formFile" class="form-label">Изображение</label>
                                <input class="form-control" type="file" id="formFile" name="image" required>
                            </div>
                            <input type="hidden" name="spot" value="плазма">

                            <hr class="my-4">
                            <button class="w-100 btn btn-primary btn-lg" type="submit">Добавить задачу</button>
                        </div>
                    </form>
                </div>
            </div>
        </main>
    </div>
</body>
{% endblock %}

skyceh/templates/tasks/spot_create.html
{% extends "base_generic.html" %}

{% block content %}
<h2>Новый заказ</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">Добавить заказ</button>
</form>
{% endblock %}

skyceh/templates/tasks/task_create.html
{% extends "base_generic.html" %}

{% block content %}
<h2>Новый заказ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать">
</form>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $("#id_spot").change(function () {
        var spot_id = $(this).val();
        $.ajax({
            url: '/load_managers/',
            data: { 'spot_id': spot_id },
            dataType: 'json',
            success: function (data) {
                var manSelect = $("#id_man");
                manSelect.empty();
                $.each(data, function (key, value) {
                    manSelect.append($("<option></option>")
                        .attr("value", value.man)
                        .text(value.man));
                });
            }
        });
    });
</script>
{% endblock %}

skyceh/templates/tasks/task_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>{{ task.dat }}</h1>
<p>Задача: {{ task.task }}</p>

{% if task.file %}
<p>Файл: <a href="{{ task.file.url }}">{{ task.file.name }}</a></p>
{% else %}
<p>Файл не загружен.</p>
{% endif %}

{% if task.image %}
<p>Изображение: <img src="{{ task.image.url }}" alt="{{ task.image.name }}"></p>
{% else %}
<p>Изображение не загружено.</p>
{% endif %}

<p>Готово: {{ task.now }} из {{ task.total }}</p>
<p>Участок: {{ task.spot }}</p>
<p>Сотрудник: {{ task.man }}</p>
<p>Срок: {{ task.deadline }}</p>
<p>Готово: {{ task.ready }}</p>

{% endblock %}

skyceh/templates/tasks/task_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class="text-center">Задачи в работе</h1>
{% if task_list %}
<table class="table table-hover table-info">
  <thead>
    <tr>
      <th scope="col">Дата</th>
      <th scope="col">Задача</th>
      <th scope="col">Файл</th>
      <th scope="col">Изображение</th>
      <th scope="col">Участок</th>
      <th scope="col">Срок</th>
    </tr>
  </thead>
  <tbody>
    {% for task in task_list %}
    {% if task.ready == False %}
    <tr>
      <th scope="row">
        <a href="#">{{ task.dat }}</a>
      </th>
      <td><a href="{{ task.get_absolute_url }}">{{ task.task }}</a></td>
      {% if task.file %}
      <td>
        Файл: <a href="{{ task.file.url }}">{{ task.file.name }}</a>
      </td>
      {% else %}
      <td>
        Файл не загружен.
      </td>
      {% endif %}

      {% if task.image %}
      <td>
        Изображение: <img src="{{ task.image.url }}" alt="{{ task.image.name }}">
      </td>
      {% else %}
      <td>
        Изображение не загружено.
      </td>
      {% endif %}
      <td>{{ task.man }}</td>
      <td>{{ task.deadline }}</td>
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>
{% endif %}


{% endblock %}